//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmasLetterAnalyzer.CognitiveServices.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmasLetterAnalyzer.CognitiveServices.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a Sant Claus assistant that helps Santa Claus to read the children letters looking for their wishes for xmas gifts..
        /// </summary>
        internal static string DefaultSystemPrompt {
            get {
                return ResourceManager.GetString("DefaultSystemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze the following letter: &quot;{letterText}&quot;.
        ///Extract which gifts the child wants in the following JSON format:
        ///{
        ///	&quot;childName&quot; : &quot;name of the child&quot;,
        ///	&quot;gifts&quot; : [{
        ///		&quot;type&quot; : &quot;type of gift&quot;,
        ///		&quot;brand&quot;: &quot;brand of gift&quot;,
        ///		&quot;material&quot; : &quot;material of gift&quot;,
        ///		&quot;model&quot;: &quot;model of gift&quot;
        ///	}]
        ///}
        ///Return only the JSON.
        ///If a field is not present in the letter, it must not be present in the JSON.
        ///If you cannot extract data, return an empty string.
        ///
        ///EXAMPLE
        ///
        ///&quot;Dear Santa Claus, I&apos;m Massimo and I want a Nik [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultUserPrompt {
            get {
                return ResourceManager.GetString("DefaultUserPrompt", resourceCulture);
            }
        }
    }
}
